language: node_js
node_js:
  - 12.18.3
cache:
  directories:
   - node_modules
before_script:
 - npm run compile
 - psql -c 'create database travis_ci_test;' -U postgres
env:
 - CXX=g++-4.8 DATABASE_URL=postgres://postgres@localhost/travis_ci_test
addons:
  postgresql: "9.4"
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.8
services:
  - postgresql
