language: node_js

node_js:
  - 12.18.3
cache:
  directories:
   - node_modules
before_install:
  - docker pull postgres:11.1
  - docker run -d -p 127.0.0.1:5432:5432 -e POSTGRES_PASSWORD=password --name postgres postgres:11.1
before_script:
  - docker exec -it postgres /bin/bash -c 'psql -U postgres -c "create database travis_ci_test;"'
  - npm run compile
env:
 - CXX=g++-4.8 DATABASE_URL=postgres://postgres:password@127.0.0.1/travis_ci_test
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.8
services:
  - docker
